on:
  push:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**.yaml"
name: Build GTI
jobs:
  build_gti:
    name: Build and Test GTI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Build gti
        run: cargo build --release --all-features

      - name: Test gti
        run: cargo test
